DEFAULT_CONFIG = {
    "exclude": [
        "__pycache__",
        "node_modules",
        ".git",
        "venv",
        ".env",
        ".env.local",
        ".idea",
        ".vscode",
        "dist",
        "build",
        ".next",
        "coverage",
    ],
    "max_file_size_mb": 1,
    "include_binary_files": False,
    "show_processed_files": False,
    "estimate_tokens": False,
}
